Add friends likes
oleg-bobrikov/java-filmorate pull request #2
Opened 2023-03-09 21:18 UTC by oleg-bobrikov

Sprint 10

2023-03-10 10:14 UTC, TomattmanYandex requested changes
Привет, есть что поправить

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dto/Film.java
> +    private Set<Integer> likes;
чтобы не инициализировать обязательно пустое значение можно 
private Set<Integer> likes = new HashSet()

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/handler/CustomExceptionHandler.java
>      @ResponseStatus(HttpStatus.NOT_FOUND)
тут уже другой статус должен быть

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage;
модификаторы доступа и лучше сделать финальными

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
а про инициализацию все то же @RequiredArgsConstructor

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ValidationException("Не заполен параметр id.");
мне кажется это уже излишняя проверка, для таких случаев вешают на переменную в параметре аннотацию @NotNull

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id <= 0) {
А вот это условие уже лишнее, id могут быть любыми значениями, и порой удобнее когда они отрицательные, например может быть предустановленный список значений, и чтобы отделить их от остальных значений, им можно дать отрицательные id

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Зачем эта аннотация на методе сервиса?

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
может быть nullPointer стоит проверить на null и сам фильм чтобы ошибки не было и пользователя, чтобы не было ошибки и мы не поставили лайк от несуществующего пользователя

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
проверочки те же

2023-03-10 10:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserStorage userStorage;
аналогично с предыдущим, я думаю будет все комменты такие же как к предыдущему классу

2023-03-10 13:53 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
добавил аннотацию 
@RequiredArgsConstructor

2023-03-10 13:59 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopular(@RequestParam(required = false) Integer count) {
public List<Film> getPopular(@RequestParam(defaultValue = "10", required = false) Integer count) {

2023-03-10 14:04 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dto/Film.java
> +    private Set<Integer> likes;
такая инициализация не спасает от ручной установки через setter значения Null
И IDE тоже ругается, что это redundant- то есть избыточно

2023-03-10 14:07 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/handler/CustomExceptionHandler.java
>      @ResponseStatus(HttpStatus.NOT_FOUND)
статус заменен на
 @ResponseStatus(HttpStatus.BAD_REQUEST) 400

2023-03-10 15:13 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> friends = getUserById(id).getFriends();
NullPointerException не произойдет, так как будет выброшено другое исключение
    public User getUserById(Integer id) {
        if (id == null) {
            throw new ValidationException("Не заполен параметр id.");
        }

        User user = userStorage.getUserById(id);
        if (user == null) {
            throw new NotFoundException("Пользователь с идентификатором " + id + " не найден.");
        }

        return user;
    }

2023-03-10 15:19 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (friends == null || otherFriends == null) {
Удалена дополнительная проверка, так как если 
friends == null || otherFriends == null,
то другие исключения сработают раньше

2023-03-10 15:20 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .getUserById(id)
Да, точно.
Конструкция userStorage.getUserById(id) заменена на
friends

2023-03-10 16:09 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film add(Film film);
видимо не нажал 
Ctrl-A
Ctrl-Alt-Enter 
для форматирования

2023-03-11 13:13 UTC, TomattmanYandex approved these changes
Принято

2023-03-11 14:56 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage;
private final FilmStorage filmStorage;
  private final UserService userService;

2023-03-11 14:57 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
Добавлен
@RequiredArgsConstructor

2023-03-11 14:57 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ValidationException("Не заполен параметр id.");
логика перенесена  в контроллер

2023-03-11 14:58 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id <= 0) {
валидация реализована через аннотацию

2023-03-11 14:59 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
удалена лишняя аннотация
    @ResponseStatus(HttpStatus.NO_CONTENT)

2023-03-11 14:59 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
валидация сделана в контроллере

2023-03-11 14:59 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
валидация ушла в контроллер

2023-03-11 15:00 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserStorage userStorage;
исправлено

2023-03-11 15:05 UTC, merged