Сдача группового проекта 12 спринта
oleg-bobrikov/java-filmorate pull request #24
Opened 2023-06-15 20:38 UTC by oleg-bobrikov

2023-06-17 12:03 UTC, TomattmanYandex requested changes
Привет, вы добрались до группового проекта. Он включает в себя много под заданий и поэтому комментариев тоже много.
Что мне очень нравится, так что, что проект выглядит так, что создается впечатление, что вы собрались сначала и сразу определились со стилем и подходом написания кода. Даже залез в историю коммитов, чтобы проверить, точно ли не один человек все коммитил)
Теперь по самому проекту
Я думаю это самая большая проблема текущей реализацию У вас большинство бизнес логики завязано на базу данных, т.е. сервисы кажется нужны только для того чтобы провалидировать входные данные и вызвать методы из уровня хранилища
Стандартный подход при реализации приложений, особенно на ранних этапах, это наоборот  добавить максимум логики в сервисы, используя простейшие конструкции при обращении к базе, например ваша задача по поиску популярных фильмов по жанрам и годам могла бы быть выполнена, как найти все фильмы с сортировкой по популярности, а потом на уровне сервиса, отфильтровать их по нужным данным. а уже после того как есть базовая рабочая версия, все оптимизируется, усложняются запросы, и т.д.
И это удобнее по двум причинам, 
1) поддерживаемость (изменить что то в хорошо написанном джава коде гораздо проще чем в полотнище сложного sql запроса)
2) простота дебага (я не знаю как продебажить sql запрос и понять почему он возвращает не те данные)

Вы первая команда, которая сделала реализацию ивентов по триггерам базы данных. Если вся команда хорошо понимает как это работает, и способна это поддерживать, то никаких проблем с этим нету, если нет, то лучше сделать стандартным подходом, с сервисом который будет создавать ивенты, и когда они происходят на уровне других сервисов, там же и вызывать создающий метод event сервиса

А теперь, то, что вызовет самую большую проблему при исправлении, и почему исправление заставит вас страдать, и почему я делаю акцент на том, что лучше бы делали  бизнес логику в сервисе (я даже специально приложу скрин) 
![image](https://github.com/oleg-bobrikov/java-filmorate/assets/113444956/28972f3c-9fca-451a-90af-ba0c79fa7d78)

Удачи с переделкой

2023-06-18 07:48 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dto/Director.java
> +package ru.yandex.practicum.filmorate.dto;
dto переименован в model

2023-06-18 07:48 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dto/Review.java
> +    public Map<String, Object> toMap() {
toMap() перенесен в сервис

2023-06-18 07:49 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void removeReview(@PathVariable @NotNull Integer id) {
удалена лишняя валидация@NutNull

2023-06-18 07:49 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review findReviewById(@PathVariable @NotNull Integer id) {
удалена лишняя валидация@nutnull

2023-06-18 07:49 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserH2Storage.java
> +                "delete from users where id = :user_id; " +
упрощен запрос с учетом on cascasde delete

2023-06-18 07:50 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +                "delete from directors_films where film_id =:film_id";
упрощен запрос с учетом on cascasde delete

2023-06-18 07:50 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (directors.isEmpty()) log.warn("Список режессеров пуст!");
добавлены фигурные скобки

2023-06-18 11:19 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +        String sqlQueryByLikes = "SELECT df.film_id, COUNT(fl.user_id) AS p " +
сделано 2 метода:
 List<Film> searchFilmsByDirectorOrderedByYear(Integer directorId);
 List<Film> searchFilmsByDirectorOrderedByLikes(Integer directorId);

2023-06-18 11:57 UTC, oleg-bobrikov commented on README.md
> + ![img.png](img.png)
добавлено описание

2023-06-18 11:58 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void like(@PathVariable @NotNull Integer reviewId, @PathVariable @NotNull Integer userId) {
поправлено

2023-06-18 12:04 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void removeAnyLike(@PathVariable @NotNull Integer reviewId, @PathVariable @NotNull Integer userId) {
Существует 2 типа лайков - Like и DisLike
Метод any означает, что удалить можно любой из этих типов лайков
removeAnyLike переименован в removeAnyReviewLike

2023-06-18 13:01 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            Film film = filmService.getFilmById(filmId.get());
Это нужно для проверки Not found Exception.
Функционал перенесен из контроллера в сервис.
Дважды реализовывать нет смысла из-за дублирования кода

2023-06-18 13:02 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        if (filmId.isPresent()) {
Это нужно для проверки Not found Exception.
Функционал перенесен из контроллера в сервис.
Дважды реализовывать нет смысла из-за дублирования кода

2023-06-18 13:09 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> reviewOpt = reviewStorage.add(review);
сделан throw new DataBaseException("Ошибка получения отзыва по идентификатору " + review.getReviewId())
в storage.
Option уделен

2023-06-18 13:15 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (reviewOpt.isPresent()) {
сделан throw new DataBaseException("Ошибка получения отзыва по идентификатору " + review.getReviewId())
в storage.
Option уделен

2023-06-18 13:25 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> reviewOptional = reviewStorage.findReviewById(id);
переделано на 
return reviewStorage.findReviewById(id).orElseThrow(
                () -> new NotFoundException("Отзыв с идентификатором " + id + " не найден."));

2023-06-18 13:40 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.addAnyLike(reviewLike);
все дело в требованиях, согласно которому один метод должен 2 вещи делать:
удалять как лайки, так и дизлайки.
Но с точки зрения СУБД это можно сделать одним запросом.

DELETE /reviews/{id}/like/{userId} — пользователь удаляет лайк/дизлайк отзыву.
мой метод был универсальный - он удалял и лайк и дизлайк

2023-06-18 14:41 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.addAnyLike(reviewLike);
переименованы методы

2023-06-18 14:41 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void removeDislike(Integer reviewId, Integer userId) {
метод удален

2023-06-18 14:45 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        findReviewById(reviewId);
этот кейс предусмотрен на уровне СУБД.
В случае ошибки вставка индекса будет неуникальна

2023-06-18 14:45 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewH2Storage.java
> +    public void removeDislike(ReviewLike reviewLike) {
оставлен один метод

2023-06-18 15:12 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +    public List<Film> searchFilms(Map<String, String> params) {
поскольку запрос используется один и тот же, то вышеприведенный комментарий приводит к избыточности кода.
запрос не такой уж и большой и читается вполне даже.
Наоборот, обработка данных в java излишне, когда все это можно и нужно переложить на плечи СУБД.
Если есть возможность отфильтровать какие-то данные в СУБД, то лучше это сделать в СУБД,  а не тянуть миллионные строчки в JAVA, чтобы потом их отфильтровать.

2023-06-18 15:12 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +    public List<Film> searchFilms(Map<String, String> params) {
в данном случае используется шаблон проектирования DRY -don't repeat yourself

2023-06-18 15:31 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +    public List<Film> getPopularFilmsSortedByGenre(Integer count, Integer genreId) {
переименовано

2023-06-18 18:49 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void removeAnyLike(@PathVariable @NotNull Integer reviewId, @PathVariable @NotNull Integer userId) {
в итоге метод переименован в removeReviewLikeOrDislike

2023-06-18 18:50 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +    public void removeFilmById(Integer id) {
класс удален

2023-06-18 18:50 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryUserStorage.java
> +    public List<User> findUserFriendsById(int id) {
класс удален

2023-06-18 18:51 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (query.isEmpty() || by.isEmpty()) {
логика реализована в сервисе

2023-06-18 20:48 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +    public List<Film> searchFilms(Map<String, String> params) {
Для простоты вызова 
добавлены методы
 List<Film> searchFilmsByDirectorName(String s);
 List<Film> searchFilmsByTitle(String s);
 List<Film> searchFilmsByTitleAndDirectorName(String s);

Для соблюдения принципа DRY - don't repeat yourself 
оставлен метод
searchFilms()
реализующий общий запрос.

Что касается отладки запросов, то мне лично удобнее отлаживать в специальных средах,
например,
DBEaver, MS SQL Server Managemnet, pgadmin и других утилит.

2023-06-18 21:04 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +        String sql = "SELECT" +
1. выполнен
2. выполнен
3.-4 пункт выполнены в одном запросе.

2023-06-19 08:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void removeAnyLike(@PathVariable @NotNull Integer reviewId, @PathVariable @NotNull Integer userId) {
так как класс модели называется ReviewLIke И она используется и для лайков и для дизлайков, то можно было бы сделать имя покороче removeReviewLike  (вообще учитывая что метод в review контроллере можно было бы сделать просто removeLike)
исправлять не обязательно, просто как рассуждение

2023-06-19 08:35 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        findReviewById(reviewId);
отлично увидел, разве что иногда лучше не доводить до эксепшена, если можем проверить на то, будет ли он

2023-06-19 08:40 UTC, TomattmanYandex approved these changes
Молодцы принято

2023-06-19 18:07 UTC, oleg-bobrikov commented
ok

2023-06-19 18:37 UTC, merged