Add database
oleg-bobrikov/java-filmorate pull request #3
Opened 2023-04-22 06:25 UTC by oleg-bobrikov

2023-04-22 15:49 UTC, TomattmanYandex requested changes
не хватает картинки со схемой базы
А так работа хорошая, но стоит убрать из схемы View и делать стандартные запросы
а еще стоит сделать одинаковый инжект зависимостей рекомендую через privat final компоненты и RequiredArgsConstructor
ну и навести порядок в в хранилищах и Dao по сути это одно и то же но почему то дублируется

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
это аннотация тут не нужна, компонент заинжектится через конструктор

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +public class FilmDaoImplH2 implements FilmDao {
H2 часть в названии избыточна (для всех дао но там я этот комент оставлять не буду) так как этот компонент будет работать именно с базами данными, а не только с одной конкретной

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +    @Autowired
лучше инжектить зависимости через конструктор, а с учетом наличия Lombook это становится мегаудобным инструментом

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +    MpaStorage mpaStorage;
модификатор доступа
но вообще обычно компоненты уровня хранилища не сильно взаимодействуют друг с другом, связь между ними происходит на уровне сервиса

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +CREATE VIEW IF NOT EXISTS GET_FILMS AS
прикольно конечно, но очень усложняет понимание кода, вот я только что сидел и пытался понять откуда от простого запроса за фильмами появился рейтинг, а оказывается запрос был сделан не к таблицам а к VIew

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +CREATE VIEW IF NOT EXISTS GET_FILMS AS
Лучше убрать и сделать обычные запросы в Dao

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +        for (Genre genre : film.getGenres()) {
было бы проще удалить все старые жанры и просто заново добавить новые

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +    public FilmDaoImplH2(JdbcTemplate jdbcTemplate) {
есть же RequiredArgsConstructor

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Интересно конечно, но зачем, если DAO можtn просто заимплементить FilmStorage

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Итого есть два интерфейса имеющие один смысл, и две имплементации, одна из которых просто проксирует запросы

2023-04-22 15:49 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
В остальных классах те же вопросы

2023-04-22 15:49 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +class FilmoRateApplicationTests {
это тест не приложения а только хранилища пользователей, а надо сделать отдельные тесты для всех Dao

2023-04-22 17:26 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
удали    @Autowired

2023-04-22 17:28 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +public class FilmDaoImplH2 implements FilmDao {
H2 часть в названии не избыточна, так как планируется еще компонента
filmDaoImpPostgresql
filmDaoImpMSSQL
filmDaoImpOracle

2023-04-22 17:35 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +    @Autowired
В данном конкретном случае Lombok не подходит, так как в конструкторе необходим еще 2 другие переменные определить:
`DataSource dataSource = jdbcTemplate.getDataSource();
        namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(Objects.requireNonNull(dataSource));
        generatedKeyHolder = new GeneratedKeyHolder();`

2023-04-22 17:36 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +    MpaStorage mpaStorage;
удалена нотация 
`@Autowired`

2023-04-22 17:40 UTC, oleg-bobrikov commented on src/main/resources/schema.sql
> +CREATE VIEW IF NOT EXISTS GET_FILMS AS
Дело в том, что в коде сложные запросы плохо читаются из-за того что в Intellij Idea не реализовано
форматирование sql запросов и подсветка.

2023-04-22 17:49 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +        for (Genre genre : film.getGenres()) {
Не проще. Жанры, которые передаются из Postman - "битые" - есть только идентификатор.
Чтобы сформировать полный объект, необходимо получить жанр заново из базы данных, 
то есть восстановить его по идентификатору.
Метод 
GenreDaoImplH2.updateFilmGenres(Film film, Set<Genre> genres) 
как раз удаляет жанры и добавляет новые.

2023-04-22 17:51 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +    public FilmDaoImplH2(JdbcTemplate jdbcTemplate) {
Кроме компонент Spring, есть еще и другие поля, которые нужны в конструкторе.
Поэтому нотация @RequiredArgsConstructor не может инициализировать еще несколько полей.
`public FilmDaoImplH2(JdbcTemplate jdbcTemplate, GenreStorage genreStorage, MpaStorage mpaStorage) {
        this.jdbcTemplate = jdbcTemplate;
        this.genreStorage = genreStorage;
        this.mpaStorage = mpaStorage;
        DataSource dataSource = jdbcTemplate.getDataSource();
        namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(Objects.requireNonNull(dataSource));
        generatedKeyHolder = new GeneratedKeyHolder();
    }`

2023-04-22 17:53 UTC, oleg-bobrikov commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +class FilmoRateApplicationTests {
в ТЗ была задача сделать интеграционный тест.
Наставник сказал, что достаточно 30% тестов,

2023-04-22 17:55 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImplH2.java
> +public class FilmDaoImplH2 implements FilmDao {
> не хватает картинки со схемой базы

картинка есть в readme репозитория.
Более того, есть еще и публичная ссылка на схему базы данных

2023-04-22 18:30 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Оставлен один интерфейс и реализованы имплементации

2023-04-28 09:18 UTC, TomattmanYandex requested changes
над уровнем доступа к бае следует еще поработать
1) не стоит вводить переменные только ради того чтобы они были
2) если нам нужно сделать просто выборку не следует создавать дополнительные таблицы, при работе в многопользовательской многопоточной среде, это может аукнуться
3) общие моменты стоит вынести в отдельный метод, например превращени одной строчки резалт сета в обьект или проставление допольниткельных дыннх фильму( сделать отдельный метод который будет принимать список фильмов делать запрос и проставлять им жанры потому что это надо будет во всех получениях фильмов)

2023-04-28 09:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +public class FilmH2Storage implements FilmStorage {
Я все еще утверждаю что часть с H2 не нужна, так как мы рабоатем с SQL базыой данных, и ыйд запросами, следовательно подавляющее большинство вещей который мы будем делать будет одинаковой
(синтаксис разных диалектов идентичен различны только внутренние реализации) и следовательно если и будетразделение по сервисам, то это будет только по типам баз sql И NoSql и по типу хранения в памяти (как мы делали раньше) или в реальной отдельной базе (как сейчас)

2023-04-28 09:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +        sql = "SELECT" +
зачем просто переписывать полное значнеи переменой? 
bkb cjplfnm yjde. bkb ghjcnj bcgjkmpjdfnm в следующем методе вместо значение переменной строку

2023-04-28 09:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserH2Storage.java
> +            User user = User.builder()
часть по превращению резалт сета в обьект лучше вынести в отдельный метод, так будет лучше понимать и поддерживать

2023-04-28 09:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserH2Storage.java
> +            User user = User.builder()
и можно переиспользовать

2023-04-28 13:53 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@AllArgsConstructor
если использовать конструктор @RrequiredArgsConstructor, то нужна дополнительная нотация @Autowired

2023-04-28 13:54 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +public class FilmH2Storage implements FilmStorage {
я в корне не согласен с этим утверждением, H2 очень сильно отличается от Postgres.
Большую часть запросов надо переписывать.

2023-04-28 13:58 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +        sql = "SELECT" +
я копирую запрос из другой среды разработки. Мне так легче читать запрос.

2023-04-28 18:23 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserH2Storage.java
> +            User user = User.builder()
добавлен класс UserRowMapper

2023-04-29 08:08 UTC, oleg-bobrikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserH2Storage.java
> +            User user = User.builder()
добавлен класс FIlmRowMapper

2023-04-30 15:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +public class FilmH2Storage implements FilmStorage {
опыт реальных проектов подсказывает, что как раз таки преимущество отдается тому, чтобы было проще поддерживать и универсальности, поэтому чаще всего используются довольно таки универсальные запросы

2023-04-30 15:23 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmH2Storage.java
> +        sql = "SELECT" +
хорошо, это просто про читаемость кода, и перезапись переменных

2023-04-30 15:28 UTC, TomattmanYandex approved these changes
В основном были запросы по философским вопросам. 
Обычно все такие моменты решаются на уровне архитектуры проекта. И может быть кардинально разным на разных проектах. На аргументы аргументны, понимание всего того что должно быть есть. Поэтому принято. 
Я думаю групповой проект может как то повлиять на восприятие поднятых вопросов.
Но в целом все прекрасно
P.S. извиняюсь за задержку с проверкой, расхерачил монитор и тепреь тяну со всеми работами, ибо проверять на одном экране нету никакого удовольствия, а еще всякие пиратские делишки и холивары)

2023-04-30 15:46 UTC, merged